version: '3'

services:
  apt-cacher-ng:
    build:
      context: .
    restart: unless-stopped
    image: "${REGISTRY:-sameersbn}/apt-cacher-ng:${TAG:-latest}"
    ports:
    - "3142:3142"
    volumes:
    - /data/apt-cacher-ng:/var/cache/apt-cacher-ng